name: Generate

on:
  schedule:
    - cron: '0 0 * * 0'
  push:
  pull_request:

jobs:
  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup `stable-x86_64-unknown-linux-gnu`
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable-x86_64-unknown-linux-gnu
          default: true
          profile: default

      - name: Install `cargo-generate`
        run: |
          wget -P ~/Downloads https://github.com/ashleygwilliams/cargo-generate/releases/download/v0.5.0/cargo-generate-v0.5.0-x86_64-unknown-linux-musl.tar.gz
          tar xzvf ~/Downloads/cargo-generate-v0.5.0-x86_64-unknown-linux-musl.tar.gz -C ~/Downloads
          echo "::add-path::$HOME/Downloads/cargo-generate-v0.5.0-x86_64-unknown-linux-musl"

      - name: '`cargo generate --git "$GITHUB_WORKSPACE" -n generated`'
        run: cargo generate --git "$GITHUB_WORKSPACE" -n generated
        working-directory: ..

      - name: '`cargo fmt --manifest-path ../generated/Cargo.toml -- --check`'
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --manifest-path ../generated/Cargo.toml -- --check

  build:
    strategy:
      fail-fast: false
      matrix:
        channel:
          - stable
          - beta
        target_triple:
          - x86_64-pc-windows-msvc
          - x86_64-apple-darwin
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
        include:
          - { channel: stable, target_triple: x86_64-pc-windows-msvc   , host_triple: x86_64-pc-windows-msvc  , cargo_generate_triple: x86_64-pc-windows-msvc   , os: windows-2019 }
          - { channel: stable, target_triple: x86_64-apple-darwin      , host_triple: x86_64-apple-darwin     , cargo_generate_triple: x86_64-apple-darwin      , os: macos-10.15  }
          - { channel: stable, target_triple: x86_64-unknown-linux-gnu , host_triple: x86_64-unknown-linux-gnu, cargo_generate_triple: x86_64-unknown-linux-musl, os: ubuntu-18.04 }
          - { channel: stable, target_triple: x86_64-unknown-linux-musl, host_triple: x86_64-unknown-linux-gnu, cargo_generate_triple: x86_64-unknown-linux-musl, os: ubuntu-18.04 }
          - { channel: beta  , target_triple: x86_64-pc-windows-msvc   , host_triple: x86_64-pc-windows-msvc  , cargo_generate_triple: x86_64-pc-windows-msvc   , os: windows-2019 }
          - { channel: beta  , target_triple: x86_64-apple-darwin      , host_triple: x86_64-apple-darwin     , cargo_generate_triple: x86_64-apple-darwin      , os: macos-10.15  }
          - { channel: beta  , target_triple: x86_64-unknown-linux-gnu , host_triple: x86_64-unknown-linux-gnu, cargo_generate_triple: x86_64-unknown-linux-musl, os: ubuntu-18.04 }
          - { channel: beta  , target_triple: x86_64-unknown-linux-musl, host_triple: x86_64-unknown-linux-gnu, cargo_generate_triple: x86_64-unknown-linux-musl, os: ubuntu-18.04 }

    name: ${{ matrix.channel }}-${{ matrix.target_triple }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: ./template

      - name: '`sudo apt-get install musl-tools`'
        run: sudo apt-get install musl-tools
        if: matrix.target_triple == 'x86_64-unknown-linux-musl'

      - name: Install toolchain and target
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.channel }}-${{ matrix.host_triple }}
          target: ${{ matrix.target_triple }}
          default: true

      - name: 'Setup `${{ matrix.channel }}-${{ matrix.host_triple }}` (target: ${{ matrix.target_triple }})'
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.channel }}-${{ matrix.host_triple }}
          target: ${{ matrix.target_triple }}
          default: true
          profile: default

      - name: Install `cargo-generate`
        run: |
          wget -P ~/Downloads https://github.com/ashleygwilliams/cargo-generate/releases/download/v0.5.0/cargo-generate-v0.5.0-${{ matrix.cargo_generate_triple }}.tar.gz
          tar xzvf ~/Downloads/cargo-generate-v0.5.0-${{ matrix.cargo_generate_triple }}.tar.gz -C ~/Downloads
          echo "::add-path::$HOME/Downloads/cargo-generate-v0.5.0-${{ matrix.cargo_generate_triple }}"
        shell: bash

      - name: '`cargo generate --git "$GITHUB_WORKSPACE" -n generated`'
        run: cargo generate --git "$GITHUB_WORKSPACE" -n generated
        shell: bash
        working-directory: ..

      - name: '`cargo clippy --target ${{ matrix.target_triple }} --manifest-path ../generated/Cargo.toml -- -D warnings`'
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --target ${{ matrix.target_triple }} --manifest-path ../generated/Cargo.toml -- -D warnings

      - name: '`cargo test --no-fail-fast --target ${{ matrix.target_triple }} --manifest-path ../generated/Cargo.toml`'
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --no-fail-fast --target ${{ matrix.target_triple }} --manifest-path ../generated/Cargo.toml

      - name: '`cargo build --target ${{ matrix.target_triple }} --manifest-path ../generated/Cargo.toml`'
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target ${{ matrix.target_triple }} --manifest-path ../generated/Cargo.toml
